### ISSUE TITLE
Prepare for team presentation

### ISSUE THREAD

**Issue by abanks7** [study-uhp/study-uhp#1]
> _Note: This is a test issue to make sure we understand how they work._

For [E58: Experience a team presentation](http://courses.ics.hawaii.edu/ics314s20/morea/project-management/experience-team-presentation.html) we need to do a short 5 minute presentation about the team and project to the class by Zoom on April 9. 

- Introduce team/discuss bonding exercise.
- How we plan to coordinate with each other.
- “Big Picture Vision” for the application
- Present GitHub project page for the Final Project Milestone M1.

**TODO List:**

- [x] Created a GitHub organization for the project

- [x] Create two repos: one for the home page for the organization, and one for the source code.

- [x] The organization home page must describe the project and team members.

- [x] All team members must have commit access to all repositories in the organization.

- [x] All team members must have uploaded a profile picture to GitHub.

- [x] The application repo should have a set of issues, at least two per team member.

- [x] There should be one defined milestone, called “M1”.

- [x] There should be one defined project board, also called “M1”. 

- [x] The project should have three columns, “Backlog”, “In Progress”, “Done”.

- [x] Each issue’s description field should start with the line, “Do all work for this task in a branch called issue-XX”, where “XX” is replaced by the number associated with this issue. The remainder of the issue description field should outline what needs to be accomplished for this task. You can define an issue template to ensure that this template text appears in all new issues.

- [x] Each issue should be assigned to milestone M1.

- [x] Each issue should appear in the project board M1.

**Comment by abanks7** [comment]
Presentation went well. Good job guys.
